// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcceyggverorcowwpech.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjY2V5Z2d2ZXJvcmNvd3dwZWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODYwNTgsImV4cCI6MjA2MjA2MjA1OH0.gfuxVe40vyKpZQ55ZG62uN8g9NiM6wkfJLyJpY3bOQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);